# Generated by Django 5.0.3 on 2025-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(upload_to='generated/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
